### ISSUE TITLE
Add Utils classes for Pets

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [ralucarobotin/svauto#13]
PetsUtils
CategoryUtils
TagUtils

**Comment by softvision-adrian-rosu** [comment]
@softvision-oana-arbuzov added PR for this task here: 
https://github.com/ralucarobotin/svauto/pull/16

**Comment by softvision-adrian-rosu** [comment]
You should close this task after the PR is merged.

**Comment by softvision-oana-arbuzov** [comment]
Fixed with the pull request https://github.com/ralucarobotin/svauto/pull/16.
